spring.application.name=api-gateway
server.port=8763

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Config Server
spring.cloud.config.uri=http://localhost:8762

# Spring Cloud Gateway
spring.cloud.gateway.discovery.locator.enabled=true

# Gateway Routes
spring.cloud.gateway.routes[0].id=PRODUCT-SERVICE
spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/product/**

spring.cloud.gateway.routes[1].id=SHOPPING-CART-SERVICE
spring.cloud.gateway.routes[1].uri=lb://SHOPPING-CART-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/shopping-cart/**

spring.cloud.gateway.routes[2].id=PRODUCT-SERVICE-FEIGN-CLIENT
spring.cloud.gateway.routes[2].uri=lb://PRODUCT-SERVICE-FEIGN-CLIENT
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/feign-client/**
