server.port=8767

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/n11bootcamp
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# RabbitMQ (zaten ekledik ama bunlar? kesinle?tir)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# publisher confirms & returns (�nemli)
#publisher-confirm-type=correlated ile broker'a mesaj?n ula?t???n? do?rulayabiliriz;
# publisher-returns=true + mandatory=true ile routing ba?ar?s?z olursa ReturnCallback tetiklenir.
# Bu, mesaj g�venilirli?ini artt?r?r.
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true

# topology
rabbitmq.exchange=orders.exchange
rabbitmq.queue=order.created.queue
rabbitmq.routingkey=order.created

# DLQ
rabbitmq.dlx.exchange=orders.dlx.exchange
rabbitmq.dlq.queue=order.created.dlq.queue
rabbitmq.dlq.routingkey=order.created.dlq


# === SAGA / STOCK EXCHANGE & ORDER QUEUE AYARLARI ===
stock.rabbit.exchange=stock.events.exchange
stock.rabbit.reservedRoutingKey=order.stock.reserved
stock.rabbit.rejectedRoutingKey=order.stock.rejected

order.rabbit.stockReservedQueue=order.stock.reserved.queue
order.rabbit.stockRejectedQueue=order.stock.rejected.queue

# Saga: Order -> Stock (rezerv iste?i i�in routing key)
stock.rabbit.reserveRequestedRoutingKey=order.stock.reserve.requested





# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Logging
logging.level.org.springframework=INFO
