server.port=8769

# === DATABASE (PostgreSQL) ===
spring.datasource.url=jdbc:postgresql://localhost:5432/n11bootcamp
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# === RABBITMQ ===
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true

# === STOCK SERVICE QUEUE & EXCHANGE AYARLARI ===
stock.rabbit.exchange=stock.events.exchange

# Order -> (exchange, routingKey) -> Stock queue
stock.rabbit.reserveRequestedRoutingKey=order.stock.reserve.requested
stock.rabbit.reserveRequestedQueue=stock.reserve.requested.queue

# Stock -> (exchange, routingKey) -> di?er servisler
stock.rabbit.reservedRoutingKey=order.stock.reserved
stock.rabbit.rejectedRoutingKey=order.stock.rejected

# (Opsiyonel DLX / DLQ)
stock.rabbit.dlx=stock.events.dlx
stock.rabbit.dlq=stock.reserve.requested.dlq

# === EUREKA ===
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# === LOGGING ===
logging.level.org.springframework=INFO
logging.level.com.noterlerbirligi.stock_service=DEBUG
