server.port=8766

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/n11bootcamp
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# JWT (senin kullan?m?na g�re; bo?luk yok)
jwt.grant_type=client_credentials
jwt.scope=openid offline_access
jwt.issuer_uri=http://localhost:8080/realms/microservice-realm/protocol/openid-connect/token
jwt.client_id=user-service
jwt.client_secret=wisI6vNCYA1dZFezCkRgWeRjNHPlWdY8
