spring.application.name=shopping-cart-service


# Config Server Ba�lant�s�
# Docker ortam�nda CONFIG_URI de�i�keni ge�ilirse onu al�r, yoksa localhost kullan�r
spring.config.import=optional:configserver:${CONFIG_URI:http://localhost:8762}

# Profil fallback (docker/local otomatik se�ilebilir)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Eureka Client (Docker veya local �zerinden override edilebilir)
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# Management / Actuator
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator

# Di�er
spring.main.allow-bean-definition-overriding=true
spring.cloud.compatibility-verifier.enabled=false


