spring.application.name=rabbitmq

server.port = 8084
rabbitmq.queue=n11bootcamp_notification
rabbitmq.exchange=n11bootcamp_exchange
rabbitmq.routingkey=n11bootcamp_routingkey
# Rabbit MQ server properties
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
