# =========================
# API Gateway - application.properties
# =========================
spring.application.name=api-gateway
server.port=8763

# Profiles
spring.profiles.active=local
spring.profiles.include=native

# -------------------------
# Config Server (env ile override edilebilir)
# - Docker i�inde: CONFIG_URI=http://config-server:8762
# - Lokal: fallback http://localhost:8762
# -------------------------
spring.cloud.config.uri=${CONFIG_URI:http://localhost:8762}
spring.config.import=optional:configserver:${CONFIG_URI:http://localhost:8762}

# -------------------------
# Eureka (env ile override edilebilir)
# - Docker i�inde: EUREKA_URI=http://discorvery-server:8761/eureka
# - Lokal: fallback http://localhost:8761/eureka
# -------------------------
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# -------------------------
# Spring Cloud Gateway discovery locator
# - Docker ortaminnda true yapmak istersin (env ile)
# - Lokalda default false (deadlock onlemek icin)
# -------------------------
spring.cloud.gateway.discovery.locator.enabled=${GATEWAY_DISCOVERY_ENABLED:false}
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# -------------------------
# Other
# -------------------------
spring.main.allow-bean-definition-overriding=true
spring.cloud.compatibility-verifier.enabled=false

# -------------------------
# Gateway Routes
# -------------------------
spring.cloud.gateway.server.webmvc.routes[0].id=PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/product/**

spring.cloud.gateway.server.webmvc.routes[1].id=SHOPPING-CART-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://SHOPPING-CART-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/shopping-cart/**

spring.cloud.gateway.server.webmvc.routes[2].id=PRODUCT-SERVICE-FEIGN-CLIENT
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://PRODUCT-SERVICE-FEIGN-CLIENT
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/feign-client/**


spring.cloud.gateway.server.webmvc.routes[3].id=ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/orders/**
