# User Service Genel Ayarlar
spring.application.name=user-service


# Config Server Baglantisi
# Docker ortam�nda CONFIG_URI de�i�keni ge�ilirse onu al�r, yoksa localhost kullan�r
spring.config.import=optional:configserver:${CONFIG_URI:http://localhost:8762}

# Profil fallback (docker/local otomatik se�ilebilir)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Eureka Client (Docker veya local uzerinden override edilebilir)
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# Management / Actuator
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator

# Diger
spring.main.allow-bean-definition-overriding=true
spring.cloud.compatibility-verifier.enabled=false



# JWT Ayarlar�
jwt.grant_type=client_credentials
jwt.scope=openid offline_access
jwt.issuer_uri=${JWT_ISSUER_URI:http://localhost:8080/realms/microservice-realm/protocol/openid-connect/token}
jwt.client_id=user-service
jwt.client_secret=${JWT_CLIENT_SECRET:wisI6vNCYA1dZFezCkRgWeRjNHPlWdY8}


